// Generated by CoffeeScript 1.6.3
(function() {
  var app, express, playerstats;

  express = require('express');

  app = express();

  app.use(express.bodyParser());

  app.configure(function() {
    return app.use("/", express["static"](__dirname));
  });

  playerstats = {};

  playerstats.x = 100;

  playerstats.y = 100;

  player.s = 1;

  app.post('/playerstats', function(req, res) {
    return playerstats = req.body;
  });

  app.get('/playerstats', function(req, res) {
    return res.send(playerstats);
  });

  app.listen(3000);

}).call(this);

/*
//@ sourceMappingURL=server.map
*/
